language: node_js
node_js: 
    - '6.10.3'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install
  #- npm install --registry=https://registry.npm.taobao.org

before_script:

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "null395922"
  - git config user.email "444395922@qq.com"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/null395922/null395922.github.io.git
